### ISSUE TITLE
Math not rendering with pandoc filter

### ISSUE THREAD

**Issue by rrags** [frabjous/fregeifier#1]
Hi, thanks for your work on this! I've tried to test the pandoc filter out and am having no luck and would appreciate some advice. The problem is that when I apply the pandoc filter to process a tex file or a markdown file into html or docx, the math doesn't appear. Below, I show my installation steps and what I get when trying to process the example document given in your documentation.

# System info

 Debian 12

# Installation Info

## Tex

sudo apt-get install texlive-full

tlmgr install fge, grundgesetze, principia

## node and npm versions

node is version v22.12.0

npm is version 10.9.0

## Pandoc

sudo apt-get install pandoc

## mutool

pip install mupdf

## fregeifier

cd ~
git clone --depth 1 https://github.com/frabjous/fregeifier

chmod a+x fregeifier/fregeifierPandocFilter.mjs

# MWE

---

## test.md

header-includes: |
    \usepackage{grundgesetze,fge}
...

In Frege’s notation, a conditional is written like so:

:::{.fregeify}
\GGjudge\GGconditional{p}{q}
:::

## Attempt 1 

pandoc --filter fregeifier/fregeifierPandocFilter.mjs \
  test.md -o test.html --verbose

### Output

[INFO] Running filter fregeifier/fregeifierPandocFilter.mjs
[INFO] Completed filter fregeifier/fregeifierPandocFilter.mjs in 6 ms
**[INFO] Not rendering RawBlock (Format "tex") "\\GGjudge\\GGconditional{p}{q}"**

### test.html

`<p>In Frege’s notation, a conditional is written like so:</p>

<div class="fregeify">

</div>`

**Comment by frabjous** [comment]
The filter is only applied to things in math mode, so you need to do:

```
:::{.fregeify}
$$
\GGjudge\GGconditional{p}{q}
$$
:::
```

instead of

```
:::{.fregeify}
\GGjudge\GGconditional{p}{q}
:::
```

The idea is that the same code could be used without the filter when processing using a LaTeX-based pdf-engine, so the difference between math mode and non-math-mode must be respected.

P.S. Looks like you probably took the code from a bad example in the README, which I've now fixed. Sorry about that.
